### ISSUE TITLE
gettext.bind_textdomain_codeset was removed

### ISSUE THREAD

**Issue by fabaff** [jendrikseipp/rednotebook#632]
**Describe the bug**

`gettext.bind_textdomain_codeset` [was removed](https://docs.python.org/3/library/gettext.html#gettext.bind_textdomain_codeset) in Python 3.10.

```bash
Traceback (most recent call last):
  File "/usr/bin/rednotebook", line 12, in <module>
    import rednotebook.journal
  File "/usr/lib/python3.11/site-packages/rednotebook/journal.py", line 100, in <module>
    elibintl.install(GETTEXT_DOMAIN, LOCALE_PATH, libintl=None)
  File "/usr/lib/python3.11/site-packages/rednotebook/external/elibintl.py", line 472, in install
    _install(domain, localedir, True, libintl=libintl)
  File "/usr/lib/python3.11/site-packages/rednotebook/external/elibintl.py", line 431, in _install
    gettext.bind_textdomain_codeset(domain, 'UTF-8')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'gettext' has no attribute 'bind_textdomain_codeset'
```

**To Reproduce**

Lauch `rednotebook` with Python >= 3.10

**Expected behavior**
Be able to run `rednotebook`

**Versions:**
- RedNotebook version : present in 2.25
- Operating system and version: All which are shipping Python >= 3.10 by default

**Log output when reproducing bug**
See above

**Comment by jendrikseipp** [comment]
Thanks for the report! The code now skips the function if it doesn't exist. I can't test whether the translations still work on Python 3.10, however.

**Comment by jendrikseipp** [comment]
I just released a new version with the fix. Feel free to reopen if the problem persists.
